#!/usr/bin/bash

### PBS Preamble begin

#PBS -N run_mothur_8_26_2019
#PBS -l nodes=1:ppn=12
#PBS -l mem=48gb
#PBS -l walltime=8:00:00
#PBS -A pschloss_fluxod
#PBS -q fluxod
#PBS -M jmastough@gmail.com
#PBS -m abe
#PBS -j oe
#PBS -V

### PBS Preamble end

### Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then
        cd $PBS_O_WORKDIR
else
    	PBS_O_WORKDIR=$(pwd)
fi
echo "Job working directory:"
pwd
echo

mothur/mothur code/get_good_seqs.batch

mothur/mothur code/get_error.batch

mothur/mothur code/get_shared_otus.batch
